name: Run all test workflow
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: success() || failure()
        with:
          api_key: ${{ secrets.APIKEY }}
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: npm ci
      - run: npm start &
      - run: npx jest --config ./jest.config.json --collectCoverage --coverageDirectory="./coverage"
      - run: ls
      - name: Foresight test kit
        if: success() || failure()
        uses: runforesight/foresight-test-kit-action@v1
        with:
          api_key: ${{ secrets.APIKEY }}
          test_format: JUNIT
          test_framework: JEST
          test_path: junit.xml
          coverage_format: COBERTURA/XML
          coverage_path: ./coverage/cobertura-coverage.xml
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage-report
          path: ./coverage
